import os
def find_prj_root(path=os.getcwd()):
    if os.path.isfile(os.path.join(path,".PRJ_ROOT")):
        return path
    else:
        if path:
            return find_prj_root(os.path.dirname(path))
        else:
            raise Exception("Can not find the PRJ_ROOT directory")

PRJ_ROOT=find_prj_root()
ROOT = os.path.dirname(PRJ_ROOT)
SRC_DIR=PRJ_ROOT+'/local/src'
SHR_DIR=PRJ_ROOT+'/local/share'
BIN_DIR=PRJ_ROOT+'/local/bin'

OS="unix"                           #unix/windows
INPUT_PATH=""                       #path to the directory containing the samples to upload
#https://snakemake.readthedocs.io/en/stable/project_info/faq.html#is-it-possible-to-pass-variable-values-to-the-workflow-via-the-command-line
EGA_USER= os.environ.get("USER")     #EGA submission portal username (the user should type it before calling snakemake)
EGA_PWD= os.environ.get("PWD")     #EGA submission portal password (the user should type it before calling snakemake)
METADATA_PATH=""    #Path to metadata (.csv)


