import os
import pandas as pd
def find_prj_root(path=os.getcwd()):
    if os.path.isfile(os.path.join(path,".PRJ_ROOT")):
        return path
    else:
        if path:
            return find_prj_root(os.path.dirname(path))
        else:
            raise Exception("Can not find the PRJ_ROOT directory")

PRJ_ROOT=find_prj_root()
ROOT = os.path.dirname(PRJ_ROOT)
SRC_DIR=PRJ_ROOT+'/local/src'
SHR_DIR=PRJ_ROOT+'/local/share'
BIN_DIR=PRJ_ROOT+'/local/bin'
DATA=SHR_DIR + "/data"
DATASET=PRJ_ROOT+"/dataset"
LOGS=DATASET+'/encrypting-uploading/logs'
DONE=LOGS+"/done"
USER_FOLDER=DATASET+'/user_folder'
CSV=USER_FOLDER+'/metadata'

### User credentials
EGA_USER="ega-box-1923"#os.environ.get("EGA_USER") # EGA submission portal username (the user should type it before calling snakemake)
EGA_PWD="7RBCduC8"#os.environ.get("EGA_PWD") # EGA submission portal password (the user should type it before calling snakemake)

FTP_TRANSFER=BIN_DIR+"/ftp_transfer"
EGA_CRYPTOR=BIN_DIR+"/ega-cryptor-2.0.0.jar"

EGA_BOX="ftp.ega.ebi.ac.uk"

### User settings
PROJECT_NAME=os.environ.get("PROJECT_NAME") # Project name
INPUT_PATH=USER_FOLDER+"/metadata/Samples_Informations_3cols.tsv" # path to the directory containing the samples to upload
OUTPUT_PATH=DATASET+'/encrypting-uploading/EGACryptor' # path to the directory to store encrypted data

FILEPATHS = []
with open(INPUT_PATH, "r") as f:
    FILEPATHS = f.read().splitlines()

SAMPLES=[]
FILES=[]
PATHS={}
for line in FILEPATHS:
    s, f, p = line.split("\t")
    SAMPLES.append(s)
    FILES.append(f)
    PATHS[s] = p

def getNames(wildcards):
    names = []
    import os
    file = CSV+"/All_files-names.txt"
    if not os.path.isfile(file):
        file = checkpoints.paths.get().output.samples
    with open(file, 'r') as fn:
        for line in fn.readlines():
            names.append(line.strip())
    return names
